//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDatHang
    {
        public int MaChiTietDDH { get; set; }
        public Nullable<int> MaDDH { get; set; }
        public Nullable<int> MaSp { get; set; }
        public string TenSp { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DonDathang DonDathang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
