//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int IDComment { get; set; }
        public string Content { get; set; }
        public Nullable<int> IDMember { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<System.DateTime> DateComment { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Member Member { get; set; }
    }
}
