//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberType_Role
    {
        public string RoleID { get; set; }
        public int MemberTypeID { get; set; }
        public string Note { get; set; }
    
        public virtual MemberType MemberType { get; set; }
        public virtual Role Role { get; set; }
    }
}
