//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.TheOrderDetails = new HashSet<TheOrderDetail>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Preferential { get; set; }
        public Nullable<bool> isCancel { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheOrderDetail> TheOrderDetails { get; set; }
    }
}
