//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.TheOrderDetails = new HashSet<TheOrderDetail>();
            this.ReceiveVoucherDetails = new HashSet<ReceiveVoucherDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Config { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public Nullable<int> VoteNumber { get; set; }
        public Nullable<int> CommentNumber { get; set; }
        public Nullable<int> BuyNumber { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ProducerID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string image3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Producer Producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheOrderDetail> TheOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveVoucherDetail> ReceiveVoucherDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
