//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveVoucherDetail
    {
        public int IDDetail { get; set; }
        public Nullable<int> ReceiveVoucherID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ReceiveVoucher ReceiveVoucher { get; set; }
    }
}
